### PR TITLE
Update inbox.jsp

### PR DESCRIPTION
**Pull request by Manish-Kumar-Vats**
changed css for input-message class

### CODE REVIEW

**Review by Manish-Kumar-Vats — COMMENTED** [review]
done

**Review by Lakhiwal — APPROVED** [review]
thanks for the changes

**Review by Lakhiwal — APPROVED** [review]

**Review by Manish-Kumar-Vats — COMMENTED** [review]
done

**Review by Lakhiwal — COMMENTED** [review]
thanks

**Pull request merged**
