### PR TITLE
Updated error404.html

### PR DESCRIPTION
**Pull request by ad1tya-v3rma**
changed explicit language used

### CODE REVIEW

**Comment by ad1tya-v3rma** [comment]
changed explicit language

**Review by Lakhiwal — COMMENTED** [review]
changed done

**Review by ad1tya-v3rma — COMMENTED** [review]
done

**Review by Lakhiwal — COMMENTED** [review]
change done

**Review by Lakhiwal — COMMENTED** [review]
thanks

**Review by Lakhiwal — COMMENTED** [review]
thanks

**Review by Lakhiwal — COMMENTED** [review]
done

**Pull request merged**
